import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from './style.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>GoPlus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to GoPlus!
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://qiniu.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/qiniu.svg" alt="Qiniu Logo" width={78} height={22} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
